version: '2'

services:
  phpfpm:
    extends:
      file: docker-compose.base.yml
      service: phpfpm-base
    volumes:
      - ./conf/phpfpm/config:/usr/local/etc
      - ./src/php:/var/www/html
    links:
      - redis0cache
    networks:
      - back_end

  #cache container
  redis0cache:
    extends:
      file: docker-compose.base.yml
      service: redis-base
    volumes:
      - ./conf/redis/config:/usr/local/etc/redis
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - back_end

networks:
  back_end:
