version: '2'

services:
  #cache container
  redis0cache:
    extends:
      file: docker-compose.base.yml
      service: redis-base
    volumes:
      - ./conf/redis/config:/usr/local/etc/redis
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - back_end

networks:
  back_end:
